name = "brutalist"
license = "Apache-2.0"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0"
description = "Brutalist theme"
homepage = "https://markruler.github.io/"
tags = ["blog", "brutalist"]
features = ["blog"]
min_version = "0.92.0"

[author]
  name = "Im Changsu"
  homepage = "https://markruler.github.io/"
